[package]
name = "wppr"
version = "0.1.0"
authors = ["Otto Rask"]

[dependencies]
clap = "^2.31"
toml = "^0.4"
serde = "^1.0"
serde_derive = "1.0"
regex = "^0.2"
prettytable-rs = "^0.6"
fs_extra = "1.1.0"

[dev-dependencies]
assert_cli = "^0.5"
text-diff = "^0.4"
